### ISSUE TITLE
Make a function that aggregates A matrices

### ISSUE THREAD

**Issue by JanetMatsen** [JanetMatsen/bacteriopop#10]
Aggregate the A matrices as Pearl's diagrams shows.  

We can use the (not yet implemented) seaborn heatmap function.

**Comment by Saghar-Hosseini** [comment]
I am concatenating the data frame since they have different dimensions across the replicates, and then use groupby to calculate their mean and STD. 
For the SNR (Mean/STD) I'm using a simple division.
