### ISSUE TITLE
Complex number warning

### ISSUE THREAD

**Issue by JanetMatsen** [JanetMatsen/bacteriopop#18]
`# Only pull out species that have interactions with another member with magnitude greater than 0.5
mappings, nodes = net.reduce_all_adjacency_matrixes_in_dict(mappings, nodes, 0.5)`

Error:
`network_construction.py:105: ComplexWarning: Casting complex values to real discards the imaginary part
  new_adj[i][j] = adj[node1][node2]`

See: Generate_Poster_Graphics.ipynb

**Comment by JanetMatsen** [comment]
Since the pandas panels ended up working great, I removed Saghar's function that threw complex number warnings. 

See: https://github.com/JanetMatsen/bacteriopop/commit/6fc9eb598b468c41d7865bfb3105f564cc1d6ac8

**Comment by JanetMatsen** [comment]
This is still a problem.  I thought the complex number error was for remove aggregate_adjacency_matrix_over_replicates(), which is depreciated.  But it is for this function, which we want to keep.

**Comment by Saghar-Hosseini** [comment]
I made a mistake in defining a diag of vectors and defined its elements type to be complex. It's fixed now :)

**Comment by JanetMatsen** [comment]
Nice catch!
